Use aserradero;

-- Insertamos datos
INSERT INTO MUNICIPIO VALUES
("Abejones", "Oaxaca", ""),
("Acatlán de Pérez Figueroa", "Oaxaca", ""),
("Asunción Cacalotepec", "Oaxaca", ""),
("Asunción Cuyotepeji", "Oaxaca", ""),
("Asunción Ixtaltepec", "Oaxaca", ""),
("Asunción Nochixtlán", "Oaxaca", ""),
("Asunción Ocotlán", "Oaxaca", ""),
("Asunción Tlacolulita", "Oaxaca", ""),
("Ayotzintepec", "Oaxaca", ""),
("El Barrio de la Soledad", "Oaxaca", ""),
("Calihualá", "Oaxaca", ""),
("Candelaria Loxicha", "Oaxaca", ""),
("Ciénega de Zimatlán", "Oaxaca", ""),
("Ciudad Ixtepec", "Oaxaca", ""),
("Coatecas Altas", "Oaxaca", ""),
("Coicoyán de las Flores", "Oaxaca", ""),
("La Compañía", "Oaxaca", ""),
("Concepción Buenavista", "Oaxaca", ""),
("Concepción Pápalo", "Oaxaca", ""),
("Constancia del Rosario", "Oaxaca", ""),
("Cosolapa", "Oaxaca", ""),
("Cosoltepec", "Oaxaca", ""),
("Cuilápam de Guerrero", "Oaxaca", ""),
("Cuyamecalco Villa de Zaragoza", "Oaxaca", ""),
("Chahuites", "Oaxaca", ""),
("Chalcatongo de Hidalgo", "Oaxaca", ""),
("Chiquihuitlán de Benito Juárez", "Oaxaca", ""),
("Heroica Ciudad de Ejutla de Crespo", "Oaxaca", ""),
("Eloxochitlán de Flores Magón", "Oaxaca", ""),
("El Espinal", "Oaxaca", ""),
("Tamazulapam del Espíritu Santo", "Oaxaca", ""),
("Fresnillo de Trujano", "Oaxaca", ""),
("Guadalupe Etla", "Oaxaca", ""),
("Guadalupe de Ramírez", "Oaxaca", ""),
("Guelatao de Juárez", "Oaxaca", ""),
("Guevea de Humboldt", "Oaxaca", ""),
("Mesones Hidalgo", "Oaxaca", ""),
("Villa Hidalgo", "Oaxaca", ""),
("Heroica Ciudad de Huajuapan de León", "Oaxaca", ""),
("Huautepec", "Oaxaca", ""),
("Huautla de Jiménez", "Oaxaca", ""),
("Ixtlán de Juárez", "Oaxaca", ""),
("Heroica Ciudad de Juchitán de Zaragoza", "Oaxaca", ""),
("Loma Bonita", "Oaxaca", ""),
("Magdalena Apasco", "Oaxaca", ""),
("Magdalena Jaltepec", "Oaxaca", ""),
("Santa Magdalena Jicotlán", "Oaxaca", ""),
("Magdalena Mixtepec", "Oaxaca", ""),
("Magdalena Ocotlán", "Oaxaca", ""),
("Magdalena Peñasco", "Oaxaca", ""),
("Magdalena Teitipac", "Oaxaca", ""),
("Magdalena Tequisistlán", "Oaxaca", ""),
("Magdalena Tlacotepec", "Oaxaca", ""),
("Magdalena Zahuatlán", "Oaxaca", ""),
("Mariscala de Juárez", "Oaxaca", ""),
("Mártires de Tacubaya", "Oaxaca", ""),
("Matías Romero Avendaño", "Oaxaca", ""),
("Mazatlán Villa de Flores", "Oaxaca", ""),
("Miahuatlán de Porfirio Díaz", "Oaxaca", ""),
("Mixistlán de la Reforma", "Oaxaca", ""),
("Monjas", "Oaxaca", ""),
("Natividad", "Oaxaca", ""),
("Nazareno Etla", "Oaxaca", ""),
("Nejapa de Madero", "Oaxaca", ""),
("Ixpantepec Nieves", "Oaxaca", ""),
("Santiago Niltepec", "Oaxaca", ""),
("Oaxaca de Juárez", "Oaxaca", ""),
("Ocotlán de Morelos", "Oaxaca", ""),
("La Pe", "Oaxaca", ""),
("Pinotepa de Don Luis", "Oaxaca", ""),
("Pluma Hidalgo", "Oaxaca", ""),
("San José del Progreso", "Oaxaca", ""),
("Putla Villa de Guerrero", "Oaxaca", ""),
("Santa Catarina Quioquitani", "Oaxaca", ""),
("Reforma de Pineda", "Oaxaca", ""),
("La Reforma", "Oaxaca", ""),
("Reyes Etla", "Oaxaca", ""),
("Rojas de Cuauhtémoc", "Oaxaca", ""),
("Salina Cruz", "Oaxaca", ""),
("San Agustín Amatengo", "Oaxaca", ""),
("San Agustín Atenango", "Oaxaca", ""),
("San Agustín Chayuco", "Oaxaca", ""),
("San Agustín de las Juntas", "Oaxaca", ""),
("San Agustín Etla", "Oaxaca", ""),
("San Agustín Loxicha", "Oaxaca", ""),
("San Agustín Tlacotepec", "Oaxaca", ""),
("San Agustín Yatareni", "Oaxaca", ""),
("San Andrés Cabecera Nueva", "Oaxaca", ""),
("San Andrés Dinicuiti", "Oaxaca", ""),
("San Andrés Huaxpaltepec", "Oaxaca", ""),
("San Andrés Huayapam", "Oaxaca", ""),
("San Andrés Ixtlahuaca", "Oaxaca", ""),
("San Andrés Lagunas", "Oaxaca", ""),
("San Andrés Nuxiño", "Oaxaca", ""),
("San Andrés Paxtlán", "Oaxaca", ""),
("San Andrés Sinaxtla", "Oaxaca", ""),
("San Andrés Solaga", "Oaxaca", ""),
("San Andrés Teotilálpam", "Oaxaca", ""),
("San Andrés Tepetlapa", "Oaxaca", ""),
("San Andrés Yaá", "Oaxaca", ""),
("San Andrés Zabache", "Oaxaca", ""),
("San Andrés Zautla", "Oaxaca", ""),
("San Antonino Castillo Velasco", "Oaxaca", ""),
("San Antonino el Alto", "Oaxaca", ""),
("San Antonino Monte Verde", "Oaxaca", ""),
("San Antonio Acutla", "Oaxaca", ""),
("San Antonio de la Cal", "Oaxaca", ""),
("San Antonio Huitepec", "Oaxaca", ""),
("San Antonio Nanahuatipam", "Oaxaca", ""),
("San Antonio Sinicahua", "Oaxaca", ""),
("San Antonio Tepetlapa", "Oaxaca", ""),
("San Baltazar Chichicapam", "Oaxaca", ""),
("San Baltazar Loxicha", "Oaxaca", ""),
("San Baltazar Yatzachi el Bajo", "Oaxaca", ""),
("San Bartolo Coyotepec", "Oaxaca", ""),
("San Bartolomé Ayautla", "Oaxaca", ""),
("San Bartolomé Loxicha", "Oaxaca", ""),
("San Bartolomé Quialana", "Oaxaca", ""),
("San Bartolomé Yucuañe", "Oaxaca", ""),
("San Bartolomé Zoogocho", "Oaxaca", ""),
("San Bartolo Soyaltepec", "Oaxaca", ""),
("San Bartolo Yautepec", "Oaxaca", ""),
("San Bernardo Mixtepec", "Oaxaca", ""),
("San Blas Atempa", "Oaxaca", ""),
("San Carlos Yautepec", "Oaxaca", ""),
("San Cristóbal Amatlán", "Oaxaca", ""),
("San Cristóbal Amoltepec", "Oaxaca", ""),
("San Cristóbal Lachirioag", "Oaxaca", ""),
("San Cristóbal Suchixtlahuaca", "Oaxaca", ""),
("San Dionisio del Mar", "Oaxaca", ""),
("San Dionisio Ocotepec", "Oaxaca", ""),
("San Dionisio Ocotlán", "Oaxaca", ""),
("San Esteban Atatlahuca", "Oaxaca", ""),
("San Felipe Jalapa de Díaz", "Oaxaca", ""),
("San Felipe Tejalapam", "Oaxaca", ""),
("San Felipe Usila", "Oaxaca", ""),
("San Francisco Cahuacúa", "Oaxaca", ""),
("San Francisco Cajonos", "Oaxaca", ""),
("San Francisco Chapulapa", "Oaxaca", ""),
("San Francisco Chindúa", "Oaxaca", ""),
("San Francisco del Mar", "Oaxaca", ""),
("San Francisco Huehuetlán", "Oaxaca", ""),
("San Francisco Ixhuatán", "Oaxaca", ""),
("San Francisco Jaltepetongo", "Oaxaca", ""),
("San Francisco Lachigoló", "Oaxaca", ""),
("San Francisco Logueche", "Oaxaca", ""),
("San Francisco Nuxaño", "Oaxaca", ""),
("San Francisco Ozolotepec", "Oaxaca", ""),
("San Francisco Sola", "Oaxaca", ""),
("San Francisco Telixtlahuaca", "Oaxaca", ""),
("San Francisco Teopan", "Oaxaca", ""),
("San Francisco Tlapancingo", "Oaxaca", ""),
("San Gabriel Mixtepec", "Oaxaca", ""),
("San Ildefonso Amatlán", "Oaxaca", ""),
("San Ildefonso Sola", "Oaxaca", ""),
("San Ildefonso Villa Alta", "Oaxaca", ""),
("San Jacinto Amilpas", "Oaxaca", ""),
("San Jacinto Tlacotepec", "Oaxaca", ""),
("San Jerónimo Coatlán", "Oaxaca", ""),
("San Jerónimo Silacayoapilla", "Oaxaca", ""),
("San Jerónimo Sosola", "Oaxaca", ""),
("San Jerónimo Taviche", "Oaxaca", ""),
("San Jerónimo Tecoatl", "Oaxaca", ""),
("San Jorge Nuchita", "Oaxaca", ""),
("San José Ayuquila", "Oaxaca", ""),
("San José Chiltepec", "Oaxaca", ""),
("San José del Peñasco", "Oaxaca", ""),
("San José Estancia Grande", "Oaxaca", ""),
("San José Independencia", "Oaxaca", ""),
("San José Lachiguirí", "Oaxaca", ""),
("San José Tenango", "Oaxaca", ""),
("San Juan Achiutla", "Oaxaca", ""),
("San Juan Atepec", "Oaxaca", ""),
("Ánimas Trujano", "Oaxaca", ""),
("San Juan Bautista Atatlahuca", "Oaxaca", ""),
("San Juan Bautista Coixtlahuaca", "Oaxaca", ""),
("San Juan Bautista Cuicatlán", "Oaxaca", ""),
("San Juan Bautista Guelache", "Oaxaca", ""),
("San Juan Bautista Jayacatlán", "Oaxaca", ""),
("San Juan Bautista Lo de Soto", "Oaxaca", ""),
("San Juan Bautista Suchitepec", "Oaxaca", ""),
("San Juan Bautista Tlacoatzintepec", "Oaxaca", ""),
("San Juan Bautista Tlachichilco", "Oaxaca", ""),
("San Juan Bautista Tuxtepec", "Oaxaca", ""),
("San Juan Cacahuatepec", "Oaxaca", ""),
("San Juan Cieneguilla", "Oaxaca", ""),
("San Juan Coatzospam", "Oaxaca", ""),
("San Juan Colorado", "Oaxaca", ""),
("San Juan Comaltepec", "Oaxaca", ""),
("San Juan Cotzocón", "Oaxaca", ""),
("San Juan Chicomezúchil", "Oaxaca", ""),
("San Juan Chilateca", "Oaxaca", ""),
("San Juan del Estado", "Oaxaca", ""),
("San Juan del Río", "Oaxaca", ""),
("San Juan Diuxi", "Oaxaca", ""),
("San Juan Evangelista Analco", "Oaxaca", ""),
("San Juan Guelavía", "Oaxaca", ""),
("San Juan Guichicovi", "Oaxaca", ""),
("San Juan Ihualtepec", "Oaxaca", ""),
("San Juan Juquila Mixes", "Oaxaca", ""),
("San Juan Juquila Vijanos", "Oaxaca", ""),
("San Juan Lachao", "Oaxaca", ""),
("San Juan Lachigalla", "Oaxaca", ""),
("San Juan Lajarcia", "Oaxaca", ""),
("San Juan Lalana", "Oaxaca", ""),
("San Juan de los Cues", "Oaxaca", ""),
("San Juan Mazatlán", "Oaxaca", ""),
("San Juan Mixtepec- Distrito Juxtlahuaca", "Oaxaca", ""),
("San Juan Mixtepec- Distrito Miahuatlán", "Oaxaca", ""),
("San Juan Ñumí", "Oaxaca", ""),
("San Juan Ozolotepec", "Oaxaca", ""),
("San Juan Petlapa", "Oaxaca", ""),
("San Juan Quiahije", "Oaxaca", ""),
("San Juan Quiotepec", "Oaxaca", ""),
("San Juan Sayultepec", "Oaxaca", ""),
("San Juan Tabaá", "Oaxaca", ""),
("San Juan Tamazola", "Oaxaca", ""),
("San Juan Teita", "Oaxaca", ""),
("San Juan Teitipac", "Oaxaca", ""),
("San Juan Tepeuxila", "Oaxaca", ""),
("San Juan Teposcolula", "Oaxaca", ""),
("San Juan Yaeé", "Oaxaca", ""),
("San Juan Yatzona", "Oaxaca", ""),
("San Juan Yucuita", "Oaxaca", ""),
("San Lorenzo", "Oaxaca", ""),
("San Lorenzo Albarradas", "Oaxaca", ""),
("San Lorenzo Cacaotepec", "Oaxaca", ""),
("San Lorenzo Cuaunecuiltitla", "Oaxaca", ""),
("San Lorenzo Texmelucan", "Oaxaca", ""),
("San Lorenzo Victoria", "Oaxaca", ""),
("San Lucas Camotlán", "Oaxaca", ""),
("San Lucas Ojitlán", "Oaxaca", ""),
("San Lucas Quiaviní", "Oaxaca", ""),
("San Lucas Zoquiapam", "Oaxaca", ""),
("San Luis Amatlán", "Oaxaca", ""),
("San Marcial Ozolotepec", "Oaxaca", ""),
("San Marcos Arteaga", "Oaxaca", ""),
("San Martín de los Cansecos", "Oaxaca", ""),
("San Martín Huamelulpam", "Oaxaca", ""),
("San Martín Itunyoso", "Oaxaca", ""),
("San Martín Lachilá", "Oaxaca", ""),
("San Martín Peras", "Oaxaca", ""),
("San Martín Tilcajete", "Oaxaca", ""),
("San Martín Toxpalan", "Oaxaca", ""),
("San Martín Zacatepec", "Oaxaca", ""),
("San Mateo Cajonos", "Oaxaca", ""),
("Capulálpam de Méndez", "Oaxaca", ""),
("San Mateo del Mar", "Oaxaca", ""),
("San Mateo Yoloxochitlán", "Oaxaca", ""),
("San Mateo Etlatongo", "Oaxaca", ""),
("San Mateo Nejapam", "Oaxaca", ""),
("San Mateo Peñasco", "Oaxaca", ""),
("San Mateo Piñas", "Oaxaca", ""),
("San Mateo Río Hondo", "Oaxaca", ""),
("San Mateo Sindihui", "Oaxaca", ""),
("San Mateo Tlapiltepec", "Oaxaca", ""),
("San Melchor Betaza", "Oaxaca", ""),
("San Miguel Achiutla", "Oaxaca", ""),
("San Miguel Ahuehuetitlán", "Oaxaca", ""),
("San Miguel Aloápam", "Oaxaca", ""),
("San Miguel Amatitlán", "Oaxaca", ""),
("San Miguel Amatlán", "Oaxaca", ""),
("San Miguel Coatlán", "Oaxaca", ""),
("San Miguel Chicahua", "Oaxaca", ""),
("San Miguel Chimalapa", "Oaxaca", ""),
("San Miguel del Puerto", "Oaxaca", ""),
("San Miguel del Río", "Oaxaca", ""),
("San Miguel Ejutla", "Oaxaca", ""),
("San Miguel el Grande", "Oaxaca", ""),
("San Miguel Huautla", "Oaxaca", ""),
("San Miguel Mixtepec", "Oaxaca", ""),
("San Miguel Panixtlahuaca", "Oaxaca", ""),
("San Miguel Peras", "Oaxaca", ""),
("San Miguel Piedras", "Oaxaca", ""),
("San Miguel Quetzaltepec", "Oaxaca", ""),
("San Miguel Santa Flor", "Oaxaca", ""),
("Villa Sola de Vega", "Oaxaca", ""),
("San Miguel Soyaltepec", "Oaxaca", ""),
("San Miguel Suchixtepec", "Oaxaca", ""),
("Villa Talea de Castro", "Oaxaca", ""),
("San Miguel Tecomatlán", "Oaxaca", ""),
("San Miguel Tenango", "Oaxaca", ""),
("San Miguel Tequixtepec", "Oaxaca", ""),
("San Miguel Tilquiapam", "Oaxaca", ""),
("San Miguel Tlacamama", "Oaxaca", ""),
("San Miguel Tlacotepec", "Oaxaca", ""),
("San Miguel Tulancingo", "Oaxaca", ""),
("San Miguel Yotao", "Oaxaca", ""),
("San Nicolás", "Oaxaca", ""),
("San Nicolás Hidalgo", "Oaxaca", ""),
("San Pablo Coatlán", "Oaxaca", ""),
("San Pablo Cuatro Venados", "Oaxaca", ""),
("San Pablo Etla", "Oaxaca", ""),
("San Pablo Huitzo", "Oaxaca", ""),
("San Pablo Huixtepec", "Oaxaca", ""),
("San Pablo Macuiltianguis", "Oaxaca", ""),
("San Pablo Tijaltepec", "Oaxaca", ""),
("San Pablo Villa de Mitla", "Oaxaca", ""),
("San Pablo Yaganiza", "Oaxaca", ""),
("San Pedro Amuzgos", "Oaxaca", ""),
("San Pedro Apóstol", "Oaxaca", ""),
("San Pedro Atoyac", "Oaxaca", ""),
("San Pedro Cajonos", "Oaxaca", ""),
("San Pedro Coxcaltepec Cántaros", "Oaxaca", ""),
("San Pedro Comitancillo", "Oaxaca", ""),
("San Pedro el Alto", "Oaxaca", ""),
("San Pedro Huamelula", "Oaxaca", ""),
("San Pedro Huilotepec", "Oaxaca", ""),
("San Pedro Ixcatlán", "Oaxaca", ""),
("San Pedro Ixtlahuaca", "Oaxaca", ""),
("San Pedro Jaltepetongo", "Oaxaca", ""),
("San Pedro Jicayán", "Oaxaca", ""),
("San Pedro Jocotipac", "Oaxaca", ""),
("San Pedro Juchatengo", "Oaxaca", ""),
("San Pedro Mártir", "Oaxaca", ""),
("San Pedro Mártir Quiechapa", "Oaxaca", ""),
("San Pedro Mártir Yucuxaco", "Oaxaca", ""),
("San Pedro Mixtepec - Distrito Juquila", "Oaxaca", ""),
("San Pedro Mixtepec - Distrito Miahuatlán", "Oaxaca", ""),
("San Pedro Molinos", "Oaxaca", ""),
("San Pedro Nopala", "Oaxaca", ""),
("San Pedro Ocopetatillo", "Oaxaca", ""),
("San Pedro Ocotepec", "Oaxaca", ""),
("San Pedro Pochutla", "Oaxaca", ""),
("San Pedro Quiatoni", "Oaxaca", ""),
("San Pedro Sochiapam", "Oaxaca", ""),
("San Pedro Tapanatepec", "Oaxaca", ""),
("San Pedro Taviche", "Oaxaca", ""),
("San Pedro Teozacoalco", "Oaxaca", ""),
("San Pedro Teutila", "Oaxaca", ""),
("San Pedro Tidaá", "Oaxaca", ""),
("San Pedro Topiltepec", "Oaxaca", ""),
("San Pedro Totolapa", "Oaxaca", ""),
("Villa de Tututepec de Melchor Ocampo", "Oaxaca", ""),
("San Pedro Yaneri", "Oaxaca", ""),
("San Pedro Yólox", "Oaxaca", ""),
("San Pedro y San Pablo Ayutla", "Oaxaca", ""),
("Villa de Etla", "Oaxaca", ""),
("San Pedro y San Pablo Teposcolula", "Oaxaca", ""),
("San Pedro y San Pablo Tequixtepec", "Oaxaca", ""),
("San Pedro Yucunama", "Oaxaca", ""),
("San Raymundo Jalpan", "Oaxaca", ""),
("San Sebastián Abasolo", "Oaxaca", ""),
("San Sebastián Coatlán", "Oaxaca", ""),
("San Sebastián Ixcapa", "Oaxaca", ""),
("San Sebastián Nicananduta", "Oaxaca", ""),
("San Sebastián Río Hondo", "Oaxaca", ""),
("San Sebastián Tecomaxtlahuaca", "Oaxaca", ""),
("San Sebastián Teitipac", "Oaxaca", ""),
("San Sebastián Tutla", "Oaxaca", ""),
("San Simón Almolongas", "Oaxaca", ""),
("San Simón Zahuatlán", "Oaxaca", ""),
("Santa Ana", "Oaxaca", ""),
("Santa Ana Ateixtlahuaca", "Oaxaca", ""),
("Santa Ana Cuauhtémoc", "Oaxaca", ""),
("Santa Ana del Valle", "Oaxaca", ""),
("Santa Ana Tavela", "Oaxaca", ""),
("Santa Ana Tlapacoyan", "Oaxaca", ""),
("Santa Ana Yareni", "Oaxaca", ""),
("Santa Ana Zegache", "Oaxaca", ""),
("Santa Catalina Quieri", "Oaxaca", ""),
("Santa Catarina Cuixtla", "Oaxaca", ""),
("Santa Catarina Ixtepeji", "Oaxaca", ""),
("Santa Catarina Juquila", "Oaxaca", ""),
("Santa Catarina Lachatao", "Oaxaca", ""),
("Santa Catarina Loxicha", "Oaxaca", ""),
("Santa Catarina Mechoacán", "Oaxaca", ""),
("Santa Catarina Minas", "Oaxaca", ""),
("Santa Catarina Quiané", "Oaxaca", ""),
("Santa Catarina Tayata", "Oaxaca", ""),
("Santa Catarina Ticuá", "Oaxaca", ""),
("Santa Catarina Yosonotú", "Oaxaca", ""),
("Santa Catarina Zapoquila", "Oaxaca", ""),
("Santa Cruz Acatepec", "Oaxaca", ""),
("Santa Cruz Amilpas", "Oaxaca", ""),
("Santa Cruz de Bravo", "Oaxaca", ""),
("Santa Cruz Itundujia", "Oaxaca", ""),
("Santa Cruz Mixtepec", "Oaxaca", ""),
("Santa Cruz Nundaco", "Oaxaca", ""),
("Santa Cruz Papalutla", "Oaxaca", ""),
("Santa Cruz Tacache de Mina", "Oaxaca", ""),
("Santa Cruz Tacahua", "Oaxaca", ""),
("Santa Cruz Tayata", "Oaxaca", ""),
("Santa Cruz Xitla", "Oaxaca", ""),
("Santa Cruz Xoxocotlán", "Oaxaca", ""),
("Santa Cruz Zenzontepec", "Oaxaca", ""),
("Santa Gertrudis", "Oaxaca", ""),
("Santa Inés del Monte", "Oaxaca", ""),
("Santa Inés Yatzeche", "Oaxaca", ""),
("Santa Lucía del Camino", "Oaxaca", ""),
("Santa Lucía Miahuatlán", "Oaxaca", ""),
("Santa Lucía Monteverde", "Oaxaca", ""),
("Santa Lucía Ocotlán", "Oaxaca", ""),
("Santa María Alotepec", "Oaxaca", ""),
("Santa María Apazco", "Oaxaca", ""),
("Santa María la Asunción", "Oaxaca", ""),
("Heroica Ciudad de Tlaxiaco", "Oaxaca", ""),
("Ayoquezco de Aldama", "Oaxaca", ""),
("Santa María Atzompa", "Oaxaca", ""),
("Santa María Camotlán", "Oaxaca", ""),
("Santa María Colotepec", "Oaxaca", ""),
("Santa María Cortijo", "Oaxaca", ""),
("Santa María Coyotepec", "Oaxaca", ""),
("Santa María Chachoapam", "Oaxaca", ""),
("Villa de Chilapa de Díaz", "Oaxaca", ""),
("Santa María Chilchotla", "Oaxaca", ""),
("Santa María Chimalapa", "Oaxaca", ""),
("Santa María del Rosario", "Oaxaca", ""),
("Santa María del Tule", "Oaxaca", ""),
("Santa María Ecatepec", "Oaxaca", ""),
("Santa María Guelacé", "Oaxaca", ""),
("Santa María Guienagati", "Oaxaca", ""),
("Santa María Huatulco", "Oaxaca", ""),
("Santa María Huazolotitlán", "Oaxaca", ""),
("Santa María Ipalapa", "Oaxaca", ""),
("Santa María Ixcatlán", "Oaxaca", ""),
("Santa María Jacatepec", "Oaxaca", ""),
("Santa María Jalapa del Marqués", "Oaxaca", ""),
("Santa María Jaltianguis", "Oaxaca", ""),
("Santa María Lachixío", "Oaxaca", ""),
("Santa María Mixtequilla", "Oaxaca", ""),
("Santa María Nativitas", "Oaxaca", ""),
("Santa María Nduayaco", "Oaxaca", ""),
("Santa María Ozolotepec", "Oaxaca", ""),
("Santa María Pápalo", "Oaxaca", ""),
("Santa María Peñoles", "Oaxaca", ""),
("Santa María Petapa", "Oaxaca", ""),
("Santa María Quiegolani", "Oaxaca", ""),
("Santa María Sola", "Oaxaca", ""),
("Santa María Tataltepec", "Oaxaca", ""),
("Santa María Tecomavaca", "Oaxaca", ""),
("Santa María Temaxcalapa", "Oaxaca", ""),
("Santa María Temaxcaltepec", "Oaxaca", ""),
("Santa María Teopoxco", "Oaxaca", ""),
("Santa María Tepantlali", "Oaxaca", ""),
("Santa María Texcatitlán", "Oaxaca", ""),
("Santa María Tlahuitoltepec", "Oaxaca", ""),
("Santa María Tlalixtac", "Oaxaca", ""),
("Santa María Tonameca", "Oaxaca", ""),
("Santa María Totolapilla", "Oaxaca", ""),
("Santa María Xadani", "Oaxaca", ""),
("Santa María Yalina", "Oaxaca", ""),
("Santa María Yavesía", "Oaxaca", ""),
("Santa María Yolotepec", "Oaxaca", ""),
("Santa María Yosoyúa", "Oaxaca", ""),
("Santa María Yucuhiti", "Oaxaca", ""),
("Santa María Zacatepec", "Oaxaca", ""),
("Santa María Zaniza", "Oaxaca", ""),
("Santa María Zoquitlán", "Oaxaca", ""),
("Santiago Amoltepec", "Oaxaca", ""),
("Santiago Apoala", "Oaxaca", ""),
("Santiago Apóstol", "Oaxaca", ""),
("Santiago Astata", "Oaxaca", ""),
("Santiago Atitlán", "Oaxaca", ""),
("Santiago Ayuquililla", "Oaxaca", ""),
("Santiago Cacaloxtepec", "Oaxaca", ""),
("Santiago Camotlán", "Oaxaca", ""),
("Santiago Comaltepec", "Oaxaca", ""),
("Santiago Chazumba", "Oaxaca", ""),
("Santiago Choapam", "Oaxaca", ""),
("Santiago del Río", "Oaxaca", ""),
("Santiago Huajolotitlán", "Oaxaca", ""),
("Santiago Huauclilla", "Oaxaca", ""),
("Santiago Ihuitlán Plumas", "Oaxaca", ""),
("Santiago Ixcuintepec", "Oaxaca", ""),
("Santiago Ixtayutla", "Oaxaca", ""),
("Santiago Jamiltepec", "Oaxaca", ""),
("Santiago Jocotepec", "Oaxaca", ""),
("Santiago Juxtlahuaca", "Oaxaca", ""),
("Santiago Lachiguiri", "Oaxaca", ""),
("Santiago Lalopa", "Oaxaca", ""),
("Santiago Laollaga", "Oaxaca", ""),
("Santiago Laxopa", "Oaxaca", ""),
("Santiago Llano Grande", "Oaxaca", ""),
("Santiago Matatlán", "Oaxaca", ""),
("Santiago Miltepec", "Oaxaca", ""),
("Santiago Minas", "Oaxaca", ""),
("Santiago Nacaltepec", "Oaxaca", ""),
("Santiago Nejapilla", "Oaxaca", ""),
("Santiago Nundiche", "Oaxaca", ""),
("Santiago Nuyoó", "Oaxaca", ""),
("Santiago Pinotepa Nacional", "Oaxaca", ""),
("Santiago Suchilquitongo", "Oaxaca", ""),
("Santiago Tamazola", "Oaxaca", ""),
("Santiago Tapextla", "Oaxaca", ""),
("Villa Tejúpam de la Unión", "Oaxaca", ""),
("Santiago Tenango", "Oaxaca", ""),
("Santiago Tepetlapa", "Oaxaca", ""),
("Santiago Tetepec", "Oaxaca", ""),
("Santiago Texcalcingo", "Oaxaca", ""),
("Santiago Textitlán", "Oaxaca", ""),
("Santiago Tilantongo", "Oaxaca", ""),
("Santiago Tillo", "Oaxaca", ""),
("Santiago Tlazoyaltepec", "Oaxaca", ""),
("Santiago Xanica", "Oaxaca", ""),
("Santiago Xiacuí", "Oaxaca", ""),
("Santiago Yaitepec", "Oaxaca", ""),
("Santiago Yaveo", "Oaxaca", ""),
("Santiago Yolomécatl", "Oaxaca", ""),
("Santiago Yosondúa", "Oaxaca", ""),
("Santiago Yucuyachi", "Oaxaca", ""),
("Santiago Zacatepec", "Oaxaca", ""),
("Santiago Zoochila", "Oaxaca", ""),
("Nuevo Zoquiapam", "Oaxaca", ""),
("Santo Domingo Ingenio", "Oaxaca", ""),
("Santo Domingo Albarradas", "Oaxaca", ""),
("Santo Domingo Armenta", "Oaxaca", ""),
("Santo Domingo Chihuitán", "Oaxaca", ""),
("Santo Domingo de Morelos", "Oaxaca", ""),
("Santo Domingo Ixcatlán", "Oaxaca", ""),
("Santo Domingo Nuxaá", "Oaxaca", ""),
("Santo Domingo Ozolotepec", "Oaxaca", ""),
("Santo Domingo Petapa", "Oaxaca", ""),
("Santo Domingo Roayaga", "Oaxaca", ""),
("Santo Domingo Tehuantepec", "Oaxaca", ""),
("Santo Domingo Teojomulco", "Oaxaca", ""),
("Santo Domingo Tepuxtepec", "Oaxaca", ""),
("Santo Domingo Tlatayapam", "Oaxaca", ""),
("Santo Domingo Tomaltepec", "Oaxaca", ""),
("Santo Domingo Tonalá", "Oaxaca", ""),
("Santo Domingo Tonaltepec", "Oaxaca", ""),
("Santo Domingo Xagacía", "Oaxaca", ""),
("Santo Domingo Yanhuitlán", "Oaxaca", ""),
("Santo Domingo Yodohino", "Oaxaca", ""),
("Santo Domingo Zanatepec", "Oaxaca", ""),
("Santos Reyes Nopala", "Oaxaca", ""),
("Santos Reyes Pápalo", "Oaxaca", ""),
("Santos Reyes Tepejillo", "Oaxaca", ""),
("Santos Reyes Yucuná", "Oaxaca", ""),
("Santo Tomás Jalieza", "Oaxaca", ""),
("Santo Tomás Mazaltepec", "Oaxaca", ""),
("Santo Tomás Ocotepec", "Oaxaca", ""),
("Santo Tomás Tamazulapan", "Oaxaca", ""),
("San Vicente Coatlán", "Oaxaca", ""),
("San Vicente Lachixío", "Oaxaca", ""),
("San Vicente Nuñú", "Oaxaca", ""),
("Silacayoapam", "Oaxaca", ""),
("Sitio de Xitlapehua", "Oaxaca", ""),
("Soledad Etla", "Oaxaca", ""),
("Villa de Tamazulapam del Progreso", "Oaxaca", ""),
("Tanetze de Zaragoza", "Oaxaca", ""),
("Taniche", "Oaxaca", ""),
("Tataltepec de Valdés", "Oaxaca", ""),
("Teococuilco de Marcos Pérez", "Oaxaca", ""),
("Teotitlán de Flores Magón", "Oaxaca", ""),
("Teotitlán del Valle", "Oaxaca", ""),
("Teotongo", "Oaxaca", ""),
("Tepelmeme Villa de Morelos", "Oaxaca", ""),
("Tezoatlán de Segura y Luna", "Oaxaca", ""),
("San Jerónimo Tlacochahuaya", "Oaxaca", ""),
("Tlacolula de Matamoros", "Oaxaca", ""),
("Tlacotepec Plumas", "Oaxaca", ""),
("Tlalixtac de Cabrera", "Oaxaca", ""),
("Totontepec Villa de Morelos", "Oaxaca", ""),
("Trinidad Zaachila", "Oaxaca", ""),
("La Trinidad Vista Hermosa", "Oaxaca", ""),
("Unión Hidalgo", "Oaxaca", ""),
("Valerio Trujano", "Oaxaca", ""),
("San Juan Bautista Valle Nacional", "Oaxaca", ""),
("Villa Díaz Ordaz", "Oaxaca", ""),
("Yaxe", "Oaxaca", ""),
("Magdalena Yodocono de Porfirio Díaz", "Oaxaca", ""),
("Yogana", "Oaxaca", ""),
("Yutanduchi de Guerrero", "Oaxaca", ""),
("Villa de Zaachila", "Oaxaca", ""),
("Zapotitlán del Río", "Oaxaca", ""),
("Zapotitlán Lagunas", "Oaxaca", ""),
("Zapotitlán Palmas", "Oaxaca", ""),
("Santa Inés de Zaragoza", "Oaxaca", ""),
("Zimatlán de Álvarez", "Oaxaca", "");

INSERT INTO LOCALIDAD (nombre_localidad,nombre_municipio,estado,telefono) VALUES 
("San Mateo Mixtepec","Santa Cruz Mixtepec",'Oaxaca','9870654321'),
("Santa Cruz Monjas","Miahuatlan de porfirio diaz",'Oaxaca','9870654322'),
('Xitla', 'Santa Cruz Xitla', 'Oaxaca','4435628711');

INSERT INTO PERSONA (id_persona,nombre,apellido_paterno,apellido_materno,nombre_localidad,nombre_municipio,estado,sexo,fecha_nacimiento,telefono) VALUES 
("MASL19931106HOCRNN","Leonardo","Marcos","Santiago","San Mateo Mixtepec","Santa Cruz Mixtepec",'Oaxaca',"H","1993-11-06","9876543210"),
("COXN20160915HOCRXX","Noe","Cortes","","Santa Cruz Monjas","Miahuatlan de porfirio diaz",'Oaxaca',"H","2016-09-15","1234567890"),
("MAXP20160916HOCRXD","Pedro","Martinez","","Santa Cruz Monjas","Miahuatlan de porfirio diaz",'Oaxaca',"H","2016-09-16","1234567890"),
("PAXA20160913HOCSXN","Antonio","Pascual","","Santa Cruz Monjas","Miahuatlan de porfirio diaz",'Oaxaca',"H","2016-09-13","1234567890"),
("PEXF20160910HOCRXR","Francisco","Perez","","Santa Cruz Monjas","Miahuatlan de porfirio diaz",'Oaxaca',"H","2016-09-10","1234567890");


DROP VIEW IF EXISTS VISTA_MUNICIPIO;
CREATE VIEW VISTA_MUNICIPIO AS
SELECT 
	nombre_municipio,
    estado,
    telefono
FROM MUNICIPIO;

DROP VIEW IF EXISTS VISTA_LOCALIDAD;
CREATE VIEW VISTA_LOCALIDAD AS 
SELECT 
	nombre_localidad,
    LOCALIDAD.nombre_municipio as nombre_municipio,
    LOCALIDAD.telefono AS telefono_localidad,
    MUNICIPIO.estado
FROM LOCALIDAD,MUNICIPIO
WHERE LOCALIDAD.nombre_municipio = MUNICIPIO.nombre_municipio
ORDER BY nombre_localidad;

-- lista a todo el personal Cliente id_cliente y nombre completo, id_jefe y nombre completo
DROP VIEW IF EXISTS PERSONAL_CLIENTE;
CREATE VIEW PERSONAL_CLIENTE AS
SELECT id_cliente,
		id_persona,
        (select concat (nombre,' ',apellido_paterno,' ',apellido_materno) FROM PERSONA WHERE PERSONA.id_persona = CLIENTE.id_persona) as cliente,
        id_jefe,
        (select concat (nombre,' ',apellido_paterno,' ',apellido_materno) as nombre FROM PERSONA WHERE id_persona = SUBSTRING(id_jefe,1,18)) as jefe
	FROM CLIENTE,ADMINISTRADOR 
	WHERE CLIENTE.id_jefe = id_administrador
    ORDER BY cliente;
-- SELECT * FROM PERSONAL_CLIENTE;

-- lista a todo el personal Proveedor id_proveedor y nombre completo, id_jefe y nombre completo
DROP VIEW IF EXISTS PERSONAL_PROVEEDOR;
CREATE VIEW PERSONAL_PROVEEDOR AS 
SELECT id_proveedor,
		id_persona,
        (select concat (nombre,' ',apellido_paterno,' ',apellido_materno) FROM PERSONA WHERE id_persona = PROVEEDOR.id_persona) as proveedor,
		id_jefe,
        (select concat (nombre,' ',apellido_paterno,' ',apellido_materno) as nombre FROM PERSONA WHERE id_persona = SUBSTRING(id_jefe,1,18)) as jefe
FROM PROVEEDOR,ADMINISTRADOR 
WHERE PROVEEDOR.id_jefe = id_administrador
ORDER BY proveedor;
-- SELECT * FROM PERSONAL_PROVEEDOR;

-- lista de vehículos con nombre completo del empleado
DROP VIEW IF EXISTS VISTA_VEHICULO;
CREATE VIEW VISTA_VEHICULO AS
SELECT id_vehiculo, 
		matricula, 
        tipo, 
        color, 
        carga_admitida, 
        motor, 
        modelo, 
        costo, 
        VEHICULO.id_empleado, 
        (select concat (nombre,' ',apellido_paterno,' ',apellido_materno) FROM EMPLEADO,PERSONA where EMPLEADO.id_persona = PERSONA.id_persona and EMPLEADO.id_empleado = VEHICULO.id_empleado) as empleado, 
        (select id_jefe FROM EMPLEADO,ADMINISTRADOR WHERE EMPLEADO.id_jefe = ADMINISTRADOR.id_administrador and EMPLEADO.id_empleado = VEHICULO.id_empleado) as id_jefe
	FROM VEHICULO;
-- SELECT * FROM VISTA_VEHICULO;

-- Disparador para crear id_cliente
DROP TRIGGER IF EXISTS CLIENTE;
DELIMITER //
CREATE TRIGGER CLIENTE BEFORE INSERT ON CLIENTE
FOR EACH ROW
BEGIN
	SET NEW.id_cliente = CONCAT(NEW.id_cliente,SUBSTRING(NEW.id_jefe,1,8));
END;//
DELIMITER ;

-- Disparador para crear id_proveedor
DROP TRIGGER IF EXISTS PROVEEDOR;
DELIMITER //
CREATE TRIGGER PROVEEDOR BEFORE INSERT ON PROVEEDOR
FOR EACH ROW
BEGIN
	SET NEW.id_proveedor = CONCAT(NEW.id_proveedor,SUBSTRING(NEW.id_jefe,1,8));
END;//
DELIMITER ;

-- disparador para insertar al proveedor como chofer
DROP TRIGGER IF EXISTS PROVEEDOR_CHOFER;
DELIMITER //
CREATE TRIGGER PROVEEDOR_CHOFER AFTER INSERT ON PROVEEDOR
FOR EACH ROW
BEGIN
	INSERT INTO EMPLEADO VALUES (NEW.id_persona,NEW.id_persona,NEW.id_jefe,'Chofer','Activo');
END;//
DELIMITER ;
SELECT * FROM EMPLEADO;
SELECT * FROM PROVEEDOR;
DROP VIEW IF EXISTS VISTA_PERSONA;
CREATE VIEW VISTA_PERSONA AS 
SELECT 
	id_persona,
    concat(nombre, ' ',apellido_paterno, ' ', apellido_materno) AS nombre,
    nombre_localidad,
    nombre_municipio,
    estado,
    direccion,
    sexo,
    fecha_nacimiento,
    telefono
FROM PERSONA
ORDER BY nombre;


DROP VIEW IF EXISTS VISTA_TERRENO;
CREATE VIEW VISTA_TERRENO AS 
SELECT 
	id_terreno,
    nombre,
    dimension,
    direccion,
    nombre_localidad,
    nombre_municipio,
    estado,
    valor_estimado,
    id_empleado,
    (SELECT CONCAT(nombre, ' ', apellido_paterno, ' ', apellido_materno) FROM PERSONA WHERE id_persona = SUBSTRING(id_empleado,1,18) LIMIT 1) AS empleado,
    (SELECT id_jefe FROM EMPLEADO WHERE id_empleado = TERRENO.id_empleado LIMIT 1) AS id_jefe
FROM TERRENO
ORDER BY nombre;
